##配置项配置
name: 黄小英111
age: 35
##服务器配置
server:
    port: 80
    tomcat:
      uri-encoding: UTF-8

##spring配置
spring:
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
  messages:
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://121.40.69.250:3306/haioutest?characterEncoding=utf-8
    username: root
    password: hutui@1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#  mail:
#    password: msznqznfjwgtbbge
#    host: smtp.qq.com
#    username: 957872488@qq.com
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
logging:
  file: ./girl/girl-service.log
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.cq.start.domain



